// Converts the designer's SVG icons (design/icons, design/ui-icons) into WPF path data.
// Output: src/Environments/UI/IconData.cs. Run: node scripts/gen-icons.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dirs = ["design/icons", "design/ui-icons"];

// Generic "program window" for apps without their own icon; not part of the design set.
const extra = {
  app: { stroke: ["M 5.5 4.5 H 18.5 A 2.5 2.5 0 0 1 21 7 V 17 A 2.5 2.5 0 0 1 18.5 19.5 H 5.5 A 2.5 2.5 0 0 1 3 17 V 7 A 2.5 2.5 0 0 1 5.5 4.5 Z", "M 3 9 H 21"], fill: [] },
};

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}="([^"]*)"`));
  return m ? m[1] : null;
};
const num = (tag, name) => parseFloat(attr(tag, name) ?? "0");
const f = n => +n.toFixed(3);

// Re-emit path data with explicit separators so WPF's parser never sees "-.8.9"-style runs.
function normalize(d) {
  const tokens = d.match(/[A-Za-z]|-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?/g) ?? [];
  return tokens.join(" ");
}

function circle(tag) {
  const cx = num(tag, "cx"), cy = num(tag, "cy"), r = num(tag, "r");
  return `M ${f(cx - r)} ${f(cy)} A ${r} ${r} 0 1 0 ${f(cx + r)} ${f(cy)} A ${r} ${r} 0 1 0 ${f(cx - r)} ${f(cy)} Z`;
}

function rect(tag) {
  const x = num(tag, "x"), y = num(tag, "y"), w = num(tag, "width"), h = num(tag, "height");
  const r = Math.min(num(tag, "rx"), w / 2, h / 2);
  if (!r) return `M ${x} ${y} H ${f(x + w)} V ${f(y + h)} H ${x} Z`;
  return [
    `M ${f(x + r)} ${y}`, `H ${f(x + w - r)}`, `A ${r} ${r} 0 0 1 ${f(x + w)} ${f(y + r)}`,
    `V ${f(y + h - r)}`, `A ${r} ${r} 0 0 1 ${f(x + w - r)} ${f(y + h)}`,
    `H ${f(x + r)}`, `A ${r} ${r} 0 0 1 ${x} ${f(y + h - r)}`,
    `V ${f(y + r)}`, `A ${r} ${r} 0 0 1 ${f(x + r)} ${y}`, "Z",
  ].join(" ");
}

const icons = {};
for (const dir of dirs) {
  for (const file of readdirSync(join(root, dir)).filter(n => n.endsWith(".svg")).sort()) {
    const svg = readFileSync(join(root, dir, file), "utf8");
    const body = svg.replace(/^<svg[^>]*>/, "");
    const stroke = [], fill = [];
    for (const tag of body.match(/<(path|circle|rect)\b[^>]*>/g) ?? []) {
      const kind = tag.match(/^<(\w+)/)[1];
      const data = kind === "path" ? normalize(attr(tag, "d")) : kind === "circle" ? circle(tag) : rect(tag);
      const filled = (attr(tag, "fill") ?? "none") !== "none";
      (filled ? fill : stroke).push(data);
    }
    icons[basename(file, ".svg")] = { stroke, fill };
  }
}
Object.assign(icons, extra);

const esc = s => s.replace(/"/g, '\\"');
const lines = Object.entries(icons).map(([name, { stroke, fill }]) =>
  `        ["${name}"] = new("${esc(stroke.join(" "))}", "${esc(fill.join(" "))}"),`);

writeFileSync(join(root, "src/Environments/UI/IconData.cs"), `// <auto-generated> by scripts/gen-icons.mjs from design/icons and design/ui-icons. Do not edit.
using System.Collections.Generic;

namespace Environments.UI;

public static partial class Icons
{
    /// <summary>24x24 line icons: stroked path data (1.75 px, round caps) and filled path data.</summary>
    static readonly Dictionary<string, (string Stroke, string Fill)> Data = new()
    {
${lines.join("\n")}
    };
}
`);
console.log(`${Object.keys(icons).length} icons`);
